export const coachTips = {
  matins: [
    "Expose-toi à la lumière naturelle dans l’heure suivant ton réveil pour renforcer ton rythme circadien.",
    "Hydrate-toi dès le réveil avec un grand verre d’eau avant le café.",
    "Prépare ton petit-déjeuner la veille pour éviter de partir à jeun.",
    "Garde une heure de coucher stable pendant les 5 matins.",
    "Évite les écrans dans les 60 minutes avant le coucher.",
    "Privilégie un petit-déjeuner avec protéines et glucides lents.",
    "Une courte marche après le poste peut t’aider à relâcher la fatigue nerveuse.",
    "Si tu ressens un creux en milieu de matinée, choisis une collation simple : fruit, yaourt ou poignée d’amandes.",
    "Évite les boissons énergisantes l’après-midi pour protéger ton sommeil du soir.",
    "Prépare tes affaires la veille pour réduire le stress du réveil.",
    "Essaie de garder une routine identique chaque matin : eau, lumière, mouvement, petit-déjeuner.",
    "Si le réveil est difficile, commence par 3 respirations profondes avant de te lever.",
    "Ne compense pas la fatigue avec trop de café : vise plutôt une meilleure récupération le soir.",
    "Après le poste, évite les siestes longues qui retardent ton coucher.",
    "Une chambre fraîche et sombre améliore la récupération entre deux matins.",
    "Mange léger le soir pour faciliter l’endormissement.",
    "Planifie les tâches importantes au moment où ton énergie est la plus stable.",
    "Une hydratation régulière aide à limiter les coups de fatigue.",
    "Prends quelques minutes pour t’étirer avant de commencer le poste.",
    "Évite de décaler fortement ton coucher pendant les jours off du bloc matin.",
    "Si tu accumules de la fatigue, privilégie une sieste courte de 20 minutes.",
    "Favorise les glucides complexes pour maintenir ton énergie plus longtemps.",
    "La régularité est ton meilleur allié pendant un bloc de 5 matins.",
    "Réduis la lumière forte le soir pour aider la mélatonine à monter.",
    "Un réveil progressif vaut mieux qu’un démarrage brutal.",
    "Prévois une bouteille d’eau accessible pendant le poste.",
    "Évite les gros repas à midi si tu as tendance à somnoler ensuite.",
    "Après le travail, prends un vrai moment de transition avant les obligations personnelles.",
    "Ton objectif principal sur les matins : éviter d’accumuler une dette de sommeil.",
    "Un petit-déjeuner simple mais complet vaut mieux qu’un départ rapide sans énergie."
  ],

  transitionJourNuit: [
    "Commence à décaler doucement ton rythme avant la première nuit.",
    "Prévois une sieste courte de 20 à 30 minutes entre 13h et 15h.",
    "Évite une sieste trop longue en fin d’après-midi : elle peut perturber l’endormissement suivant.",
    "Prends un repas léger avant la première nuit pour éviter la somnolence digestive.",
    "Décale progressivement ton dernier repas vers un horaire plus tardif.",
    "Expose-toi à la lumière en fin de journée pour aider ton corps à rester éveillé plus tard.",
    "Évite le sport intense tard le soir avant la première nuit.",
    "Prépare tes repas et collations avant le bloc de nuits.",
    "Garde une hydratation régulière avant d’attaquer la première nuit.",
    "Évite les gros desserts sucrés avant la prise de poste.",
    "L’objectif de cette transition est d’arriver à la première nuit avec le moins de dette de sommeil possible.",
    "Si tu es fatigué avant la première nuit, une micro-sieste est plus utile qu’un excès de café.",
    "Prépare ton environnement de sommeil pour le lendemain matin : chambre sombre, calme et fraîche.",
    "Préviens ton entourage de ton besoin de récupération après la nuit.",
    "Décale progressivement l’heure du coucher plutôt que de faire un changement brutal.",
    "Évite les écrans lumineux juste avant le sommeil de préparation.",
    "Privilégie une activité douce : marche, mobilité, étirements.",
    "Un repas trop gras avant la nuit peut diminuer ta vigilance.",
    "Prévois une collation protéinée pour la nuit plutôt que du sucre rapide.",
    "Organise ton retour à domicile pour pouvoir dormir rapidement après la nuit.",
    "Évite de commencer le bloc de nuit déjà déshydraté.",
    "La transition jour-nuit se prépare autant par le sommeil que par les repas.",
    "Anticipe la caféine : utile en début de nuit, moins adaptée en fin de poste.",
    "Prépare une routine calme avant le sommeil du matin.",
    "Mets en place tes outils : masque, bouchons, rideaux occultants.",
    "Plus la transition est progressive, plus la première nuit est facile à gérer.",
    "Ne cherche pas à tout décaler d’un coup : avance étape par étape.",
    "La lumière est un levier puissant pour adapter ton horloge biologique.",
    "Si tu dois faire une sieste, garde-la courte et planifiée.",
    "Ton objectif principal : arriver à la première nuit reposé, hydraté et organisé."
  ],

  nuits: [
    "Après ton poste de nuit, limite la lumière forte avant de dormir.",
    "Dors dans une chambre noire, calme et fraîche.",
    "Essaie de garder une plage de sommeil stable pendant le bloc de nuits.",
    "Prévois une collation protéinée plutôt qu’un snack très sucré.",
    "Utilise la caféine plutôt en début de nuit, évite-la en fin de poste.",
    "Hydrate-toi régulièrement, même si tu n’as pas très soif.",
    "Un repas trop lourd pendant la nuit peut favoriser la somnolence.",
    "Si possible, fais une micro-sieste de 10 à 20 minutes en cas de baisse de vigilance.",
    "Fractionner le sommeil peut être utile : sommeil principal + sieste avant le poste.",
    "Évite les écrans lumineux en rentrant si tu veux t’endormir rapidement.",
    "Prépare ton repas de nuit à l’avance pour éviter les choix impulsifs.",
    "Pendant la nuit, bouge régulièrement pour relancer la circulation.",
    "Au creux de vigilance, fais quelques respirations lentes et mobilise les épaules.",
    "Ne cherche pas à compenser la fatigue uniquement avec le sucre.",
    "Après la nuit, vise une routine courte : retour, hydratation, obscurité, sommeil.",
    "Préviens ton entourage de tes horaires de sommeil pour limiter les interruptions.",
    "Le sommeil du matin est fragile : protège-le comme un vrai rendez-vous.",
    "Une température fraîche facilite le sommeil après une nuit.",
    "Garde une bouteille d’eau près de toi pendant le poste.",
    "Évite les grandes quantités de nourriture après 3h du matin.",
    "Si ton sommeil est court, ajoute une sieste avant la prochaine nuit.",
    "Ton objectif pendant les nuits : préserver la vigilance sans détruire la récupération.",
    "La régularité du sommeil est plus importante que la perfection.",
    "Un masque occultant peut améliorer fortement la qualité du sommeil de jour.",
    "Les bouchons ou le bruit blanc peuvent aider à limiter les réveils.",
    "Une collation avec protéines et fibres tient mieux qu’un produit sucré seul.",
    "Prends quelques minutes de retour au calme avant de dormir.",
    "Évite de programmer trop d’obligations entre deux nuits.",
    "Si tu te réveilles trop tôt, reste dans un environnement calme et peu lumineux.",
    "Pendant les nuits, ton énergie doit être gérée comme une réserve limitée."
  ],

  retourJour: [
    "Après la dernière nuit, évite de dormir toute la journée.",
    "Limite le sommeil du matin à environ 3 à 5 heures pour retrouver un coucher le soir.",
    "Expose-toi à la lumière naturelle après le réveil.",
    "Reprends rapidement des repas aux horaires de jour.",
    "Évite l’excès de café pour forcer le retour au rythme de jour.",
    "Prévois une journée douce après la dernière nuit.",
    "Une marche extérieure aide ton horloge biologique à se recaler.",
    "Évite les longues siestes l’après-midi.",
    "Si tu as besoin d’une sieste, garde-la courte et avant 15h.",
    "Reprends un dîner léger pour faciliter le coucher du soir.",
    "Le retour jour demande de la patience : ne surcharge pas la première journée.",
    "Évite les écrans prolongés le soir du retour jour.",
    "Couche-toi à une heure raisonnable, même si tu ne te sens pas parfaitement fatigué.",
    "Hydrate-toi régulièrement pour aider la récupération.",
    "Privilégie une activité douce plutôt qu’un entraînement intense.",
    "Ton objectif principal : réaligner sommeil, lumière et repas.",
    "Revenir à trois repas de jour aide le corps à retrouver ses repères.",
    "Si tu es irritable, c’est souvent un signe de dette de sommeil.",
    "Prévois un moment calme en fin de journée.",
    "Évite de rester enfermé toute la journée après la dernière nuit.",
    "La lumière du matin est un signal fort pour reprendre le rythme de jour.",
    "Ne planifie pas une séance sportive intense juste après un bloc de nuits.",
    "Un petit-déjeuner structurant peut aider à relancer le rythme de jour.",
    "Réduis progressivement les comportements de nuit : grignotage tardif, lumière forte, café tardif.",
    "Le retour jour est une phase de récupération active.",
    "Évite de compenser la fatigue par des repas très sucrés.",
    "Une journée simple et organisée facilite la transition.",
    "Le soir, crée une ambiance calme et peu lumineuse.",
    "La récupération après les nuits passe autant par le repos que par la lumière.",
    "Ton objectif : redevenir fonctionnel sans t’épuiser davantage."
  ],

  joursLongs: [
    "Sur une longue journée, pense à gérer ton énergie comme une réserve.",
    "Prévois une collation toutes les 4 à 5 heures si le poste est long.",
    "Hydrate-toi par petites quantités tout au long du poste.",
    "Évite les gros repas qui provoquent une baisse d’énergie.",
    "Après un poste d’après-midi, garde un retour au calme avant de dormir.",
    "Après une journée longue, protège ton coucher pour éviter l’accumulation de fatigue.",
    "Relâche régulièrement les épaules et la mâchoire pendant le poste.",
    "Une respiration lente peut aider à réduire la tension en fin de journée.",
    "Prépare tes repas avant le poste pour éviter les choix rapides et sucrés.",
    "Le grignotage continu fatigue souvent plus qu’il n’aide.",
    "Fais de petites pauses actives si ton poste le permet.",
    "Un repas équilibré avant le poste aide à tenir sur la durée.",
    "Évite de te coucher très tard après un poste d’après-midi.",
    "La récupération commence dès la fin du poste.",
    "Après une longue journée, privilégie une routine simple : repas léger, douche, calme.",
    "Ne sous-estime pas la fatigue mentale des longues amplitudes.",
    "Planifie ton hydratation plutôt que d’attendre la soif.",
    "Les étirements courts peuvent limiter les tensions du dos et des épaules.",
    "Si tu rentres tard, évite les écrans trop stimulants.",
    "Ton objectif : tenir le poste sans sacrifier la récupération suivante.",
    "Un snack protéiné est souvent plus stable qu’un produit sucré.",
    "Fais attention aux enchaînements : plusieurs longues journées demandent une récupération stricte.",
    "Après un après-midi, évite de repousser le coucher sans raison.",
    "Une lumière tamisée le soir facilite la transition vers le sommeil.",
    "Prévois une vraie coupure mentale après le poste.",
    "Les longues journées nécessitent plus d’anticipation alimentaire.",
    "Un corps tendu récupère moins bien : relâche régulièrement les zones crispées.",
    "Si tu ressens un creux, bouge quelques minutes avant de reprendre.",
    "Évite d’arriver au poste déjà déshydraté.",
    "La clé des longues journées : régularité, pauses, hydratation et repas simples."
  ]
};
