export const didYouKnowList = [
  "Votre horloge biologique influence votre digestion, votre humeur et votre énergie.",
  "Une exposition à la lumière du matin aide à synchroniser votre rythme circadien.",
  "Dormir moins de 6 heures régulièrement augmente les risques de problèmes métaboliques.",
  "Un horaire de sommeil régulier améliore la qualité du repos.",
  "Votre température corporelle suit un cycle de 24 heures.",
  "Le manque de sommeil peut augmenter la sensation de faim.",
  "La mélatonine est produite principalement lorsque la lumière diminue.",
  "Les écrans le soir peuvent retarder l'endormissement.",
  "Le cerveau élimine davantage de déchets métaboliques pendant le sommeil profond.",
  "Les travailleurs de nuit présentent davantage de perturbations circadiennes.",
  "Une sieste courte de 10 à 20 minutes peut améliorer la vigilance.",
  "L'exercice matinal aide à renforcer le cycle veille-sommeil.",
  "Le sommeil participe à la consolidation de la mémoire.",
  "Dormir suffisamment favorise une meilleure régulation émotionnelle.",
  "La qualité du sommeil influence les performances sportives.",
  "Une chambre fraîche favorise généralement l'endormissement.",
  "Le rythme circadien régule aussi certaines hormones.",
  "Le décalage horaire perturbe temporairement les fonctions cognitives.",
  "Le manque de sommeil peut diminuer les capacités de concentration.",
  "Une activité physique régulière améliore souvent le sommeil.",
  "La lumière naturelle est le principal synchroniseur de l'horloge interne.",
  "Le sommeil aide à la récupération musculaire.",
  "Des heures de coucher irrégulières peuvent perturber le rythme biologique.",
  "Le sommeil est aussi important pour la santé que l'alimentation et l'activité physique.",

  "Les fibres favorisent la santé digestive.",
  "Les légumes colorés apportent différents antioxydants.",
  "Une bonne hydratation contribue aux fonctions cognitives.",
  "Les protéines participent à la réparation des tissus.",
  "Le petit-déjeuner n'est pas obligatoire, mais la qualité alimentaire de la journée reste essentielle.",
  "Les fruits apportent naturellement vitamines et minéraux.",
  "Les oméga-3 contribuent au fonctionnement normal du cerveau.",
  "Les légumineuses sont une excellente source de protéines végétales.",
  "Manger lentement peut favoriser une meilleure satiété.",
  "Les noix contiennent de bonnes graisses pour la santé cardiovasculaire.",
  "Une alimentation équilibrée aide à maintenir l'énergie au quotidien.",
  "Les aliments ultra-transformés sont souvent plus riches en sel, sucre et graisses.",
  "Les protéines aident à préserver la masse musculaire.",
  "Le microbiote intestinal influence de nombreux aspects de la santé.",
  "Les légumes verts sont riches en micronutriments.",
  "Le calcium contribue au maintien d'os solides.",
  "Le magnésium participe à des centaines de réactions biologiques.",
  "Les aliments complets apportent généralement plus de fibres.",
  "La vitamine D participe à la santé osseuse.",
  "Une alimentation variée réduit les risques de carences.",
  "Les protéines augmentent généralement la sensation de satiété.",
  "Le fer contribue au transport de l'oxygène dans l'organisme.",
  "Les aliments riches en eau participent à l'hydratation.",
  "Une alimentation équilibrée favorise la récupération après l'effort.",

  "Même quelques minutes d'activité sont préférables à l'inactivité.",
  "Marcher régulièrement améliore la santé cardiovasculaire.",
  "Bouger davantage réduit les effets négatifs de la sédentarité.",
  "L'activité physique améliore la qualité du sommeil.",
  "Faire de l'exercice peut réduire l'anxiété à court terme.",
  "L'activité physique contribue au maintien d'un poids sain.",
  "Les muscles restent adaptables à tout âge.",
  "Monter les escaliers est un excellent exercice cardiovasculaire.",
  "L'activité physique aide à préserver les fonctions cognitives.",
  "Une marche après les repas favorise la dépense énergétique.",
  "Le mouvement améliore la circulation sanguine.",
  "L'activité physique régulière renforce les os.",
  "Bouger aide à réduire le risque de nombreuses maladies chroniques.",
  "L'exercice améliore l'équilibre chez les personnes âgées.",
  "Les pauses actives améliorent la concentration.",
  "L'activité physique régulière est associée à une meilleure longévité.",
  "La marche rapide est une activité accessible à la plupart des adultes.",
  "L'exercice améliore la capacité cardiorespiratoire.",
  "La sédentarité prolongée est un facteur de risque pour la santé.",
  "Les exercices de renforcement complètent les activités d'endurance.",
  "Une activité physique régulière contribue à la santé mentale.",
  "Bouger davantage aide à maintenir l'autonomie avec l'âge.",
  "Les activités physiques en groupe favorisent souvent la motivation.",
  "Chaque pas compte pour la santé.",

  "Quelques minutes de respiration profonde peuvent réduire la tension ressentie.",
  "Le stress chronique peut affecter le sommeil.",
  "L'activité physique est un outil reconnu de gestion du stress.",
  "Le rire favorise la détente.",
  "La méditation peut améliorer la concentration.",
  "Marcher dans la nature favorise le bien-être psychologique.",
  "Le stress influence parfois les choix alimentaires.",
  "Une bonne qualité de sommeil améliore la résilience au stress.",
  "La cohérence cardiaque aide certaines personnes à se détendre.",
  "La gratitude régulière est associée à un meilleur bien-être.",
  "La musique relaxante peut diminuer les tensions.",
  "Les pauses régulières améliorent l'efficacité mentale.",
  "Les interactions sociales soutiennent la santé mentale.",
  "La respiration lente peut réduire la fréquence cardiaque.",
  "Le stress prolongé peut diminuer la qualité de vie.",
  "Écrire ses pensées peut aider à clarifier ses émotions.",
  "Les loisirs favorisent l'équilibre psychologique.",
  "La pleine conscience améliore la conscience de l'instant présent.",
  "La relaxation musculaire aide à relâcher les tensions corporelles.",
  "Le temps passé à l'extérieur favorise souvent la détente.",
  "Une bonne organisation réduit certaines sources de stress.",
  "Le soutien social est un facteur protecteur important.",
  "L'exercice physique libère des substances associées au bien-être.",
  "Quelques minutes de calme peuvent améliorer la clarté mentale.",

  "Le sport améliore l'endurance cardiovasculaire.",
  "La récupération fait partie intégrante de la progression.",
  "Les muscles se renforcent principalement pendant la récupération.",
  "Le sport améliore l'estime de soi.",
  "Un échauffement réduit le risque de blessure.",
  "La régularité est plus importante que l'intensité occasionnelle.",
  "Le renforcement musculaire protège les articulations.",
  "Le sport améliore la coordination motrice.",
  "L'entraînement améliore l'efficacité cardiaque.",
  "Une bonne hydratation soutient les performances.",
  "Le sport peut améliorer l'humeur dès une seule séance.",
  "Les exercices d'équilibre réduisent le risque de chute.",
  "L'entraînement progressif réduit le risque de surmenage.",
  "Les sports collectifs favorisent les liens sociaux.",
  "L'activité physique améliore la densité osseuse.",
  "Le sport aide à maintenir la masse musculaire avec l'âge.",
  "Le renforcement musculaire améliore les gestes du quotidien.",
  "Les étirements dynamiques sont adaptés à l'échauffement.",
  "Le sport contribue à réduire certains symptômes anxieux.",
  "Une meilleure condition physique améliore l'autonomie.",
  "L'entraînement améliore l'utilisation de l'oxygène par l'organisme.",
  "Les progrès viennent souvent de la constance plutôt que de l'intensité.",
  "Faire du sport en plein air peut renforcer la motivation.",
  "L'activité physique régulière est l'un des comportements les plus bénéfiques pour la santé globale.",

  "Un petit-déjeuner riche en protéines et glucides lents aide à soutenir la vigilance pendant la matinée.",
  "La digestion fonctionne au ralenti la nuit : manger léger avant la prise de poste aide à mieux rester éveillé(e).",
  "Le sucre apporte un coup de boost rapide mais souvent suivi d'une baisse d'énergie.",
  "Après les nuits, reprendre des repas classiques aide à réinitialiser l'horloge biologique.",
  "Sur une longue journée, l'énergie se gère dans la durée."
];
